name: Deploy Infraestructura AWS

on:
  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub Actions
  push:
    branches: [ "main" ]
    paths:
      - "scripts/**" # Se ejecuta si actualizas el script de infraestructura

jobs:
  build-infra:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Ejecutar script de AWS CLI
      run: |
        chmod +x ./scripts/crear-infra.sh
        ./scripts/crear-infra.sh